language: android

android:
  components:
    - build-tools-23.0.2
    - android-23
    - platform-tools
    - tools
    - extra-google-m2repository
    - extra-android-m2repository

script:
  ./gradlew build
